"""add is_receipt field in receipt table

Revision ID: 2611e68ce28f
Revises: c0b62a308f96
Create Date: 2025-06-12 10:24:12.136880

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2611e68ce28f"
down_revision: Union[str, None] = "c0b62a308f96"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("receipts", sa.Column("is_receipt", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("receipts", "is_receipt")
    # ### end Alembic commands ###
