"""renamed receipt.datetime to receipt.receipt_datetime and add receipt.scan_datetime

Revision ID: 40a0941d87e9
Revises: 2611e68ce28f
Create Date: 2025-06-16 08:59:22.621894

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "40a0941d87e9"
down_revision: Union[str, None] = "2611e68ce28f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("receipts", sa.Column("scan_datetime", sa.DateTime(), nullable=True))
    op.add_column(
        "receipts", sa.Column("receipt_datetime", sa.DateTime(), nullable=True)
    )
    op.drop_column("receipts", "datetime")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "receipts",
        sa.Column(
            "datetime", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("receipts", "receipt_datetime")
    op.drop_column("receipts", "scan_datetime")
    # ### end Alembic commands ##
