"""Add receipt fields

Revision ID: c0b62a308f96
Revises: b03a2b330c93
Create Date: 2025-06-05 11:05:27.230851

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c0b62a308f96"
down_revision: Union[str, None] = "b03a2b330c93"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("receipts", sa.Column("shop_name", sa.String(), nullable=True))
    op.add_column("receipts", sa.Column("shop_address", sa.String(), nullable=True))
    op.add_column("receipts", sa.Column("datetime", sa.DateTime(), nullable=True))
    op.add_column("receipts", sa.Column("receipt_number", sa.String(), nullable=True))
    op.add_column("receipts", sa.Column("subtotal", sa.Float(), nullable=True))
    op.add_column("receipts", sa.Column("total", sa.Float(), nullable=True))
    op.add_column("receipts", sa.Column("payment_method", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("receipts", "payment_method")
    op.drop_column("receipts", "total")
    op.drop_column("receipts", "subtotal")
    op.drop_column("receipts", "receipt_number")
    op.drop_column("receipts", "datetime")
    op.drop_column("receipts", "shop_address")
    op.drop_column("receipts", "shop_name")
    # ### end Alembic commands ###
